name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:

  testmetalwebgpu:
    name: Metal and WebGPU Tests
    runs-on: macos-13
    timeout-minutes: 20

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Cache python packages
      uses: actions/cache@v3
      with:
        path: ${{ env.Python3_ROOT_DIR }}/lib/python3.11/site-packages
        key: metal-webgpu-testing-packages-${{ hashFiles('**/setup.py') }}
    - name: Install Dependencies
      run: pip install -e '.[metal,webgpu,testing]' --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Run symbolic shapetracker test
      run: METAL=1 python -m pytest test/test_symbolic_jit.py -k test_big_cat
